### ISSUE TITLE
How come Stitch iOS documentation based on pod "NexmoConversation" while source code uses pod 'Stitch'

### ISSUE THREAD

**Issue by semeruk** [Nexmo/stitch-ios-quickstart#23]
Why is the Stitch iOS documentation based on pod "NexmoConversation" while source code starting from Quick Start Two uses pod 'Stitch'? 
There are a lot of errors when I'm trying to build it via provided documentation (https://developer.nexmo.com/stitch/in-app-messaging/guides/2-inviting-members)!

**Comment by tbass134** [comment]
@Semeruk the name changed internally from 'NexmoConversation' to 'Stitch'
in your podfile use
` pod 'Nexmo-Stitch'`

In your ViewControllers, add:
`import Stitch`

**Comment by ericgiannini** [comment]
These updates should work: 

1) `pod 'Nexmo-Stitch'`

2) `import Stitch`
