### ISSUE TITLE
Can't compile with Xcode9 & Swift 4.1

### ISSUE THREAD

**Issue by softavail** [Nexmo/stitch-ios-quickstart#30]
I tried to compile the project with Xcode 9 and got an error that a dependant module 'NexmoConversation' is compiled with Swift 4.0.3 cannot be imported in Swift 4.1.2

**Comment by tbass134** [comment]
@softavail  Please use `NexmoStitch` pod  instead of `NexmoConversation`

**Comment by tbass134** [comment]
@softavail we've updated the quickstarts to use the `NexmoStitch` pod
