### ISSUE TITLE
Swift compiler version issues fails build on Xcode 10 

### ISSUE THREAD

**Issue by altanai** [Nexmo/stitch-ios-quickstart#32]
Build fails with following errors

```
Showing All Messages
:-1: Multiple commands produce '/Users/altanaibisht/Library/Developer/Xcode/DerivedData/QuickStarts-bojinmzzqqinetghrvipslgsitkt/Build/Products/Debug-iphonesimulator/QuickStartsOne.app/Info.plist':
1) Target 'QuickStartsOne' (project 'QuickStarts') has copy command from '/Users/altanaibisht/Nexmo/stitch-ios-quickstart/examples/QuickStartOne/Supporting Files/Info.plist' to '/Users/altanaibisht/Library/Developer/Xcode/DerivedData/QuickStarts-bojinmzzqqinetghrvipslgsitkt/Build/Products/Debug-iphonesimulator/QuickStartsOne.app/Info.plist'
2) Target 'QuickStartsOne' (project 'QuickStarts') has process command with output '/Users/altanaibisht/Library/Developer/Xcode/DerivedData/QuickStarts-bojinmzzqqinetghrvipslgsitkt/Build/Products/Debug-iphonesimulator/QuickStartsOne.app/Info.plist'
```

and 

`Module compiled with Swift 4.1.2 cannot be imported by the Swift 4.2 compiler: /Users/altanaibisht/Nexmo/stitch-ios-quickstart/examples/Pods/Nexmo-Stitch/Carthage/Build/iOS/Stitch.framework/Modules/Stitch.swiftmodule/x86_64.swiftmodule`

Have tried updated pods and switching between legacy build on xcode workspace settings , Any other workarounds >

**Comment by altanai** [comment]
Error appears on module stitch
![image](https://user-images.githubusercontent.com/1989657/47633920-a0c93e80-db75-11e8-9e05-51d812fe7d70.png)

**Comment by tbass134** [comment]
@altanai the latest version of the SDK does not currently support Swift 4.2. As a workaround, you can use Xcode 9, go to https://developer.apple.com/download/more/ and search for xCode 9.4.1 
Note, you will need to sign in to your developer account
